// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const chromedriver = require('chromedriver');

module.exports = {
  // An array of folders (excluding subfolders) where your tests are located;
  // if this is not specified, the test source must be passed as the second argument to the test runner.
  src_folders: ["tests"],

  page_objects_path: './pages',
  global_path: './hooks/global.js',

  webdriver: {
    start_process: true,
    server_path: chromedriver.path,
    port: 9515
  },

  test_settings: {
    default: {
      globals: {
        waitForConditionTimeout: 15000 // Timeout Global (like Capybara)
      },
      desiredCapabilities: {
        browserName : 'chrome'
      }
    }
  }
};