// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const chromedriver = require('chromedriver');
require('geckodriver');

const testUrl = "http://zombie-web:5000"
const defaultTimeout = 15000

module.exports = {
  // An array of folders (excluding subfolders) where your tests are located;
  // if this is not specified, the test source must be passed as the second argument to the test runner.
  src_folders: ["tests"],

  page_objects_path: './pages',
  global_path: './hooks/global.js',

  webdriver: {
    start_process: true,
  },

  screenshots: {
    enabled: true,
    on_failure: true,
    on_error: true,
    path: 'tests_output/'
  },

  test_workers: {
    enabled: true
  },

  test_settings: {
    default: {
      launch_url: testUrl,
      globals: {
        waitForConditionTimeout: defaultTimeout // Timeout Global (like Capybara)
      },

      webdriver: {
        server_path: chromedriver.path,
        port: 9515
      },

      desiredCapabilities: {
        browserName : 'chrome'
      }
    },

    chrome_headless: {
      launch_url: testUrl,
      globals: {
        waitForConditionTimeout: defaultTimeout // Timeout Global (like Capybara)
      },

      webdriver: {
        server_path: chromedriver.path,
        port: 9515
      },

      desiredCapabilities: {
        browserName : 'chrome',
        chromeOptions: {
          w3c: false,
          args: ['--headless', '--no-sandbox', '--disable-dev-shm-usage']
        }
      }
    },

    firefox: {
      launch_url: testUrl,
      globals: {
        waitForConditionTimeout: defaultTimeout // Timeout Global (like Capybara)
      },

      webdriver: {
        server_path: '.\\node_modules\\.bin\\geckodriver.cmd',
        port: 4444
      },

      desiredCapabilities: {
        browserName : 'firefox',
        acceptInsecureCerts: true
      }
    },
    
    stage: {
      launch_url: "http://stage.zombieplus.com.br",
      globals: {
        waitForConditionTimeout: 15000 // Timeout Global (like Capybara)
      },
      desiredCapabilities: {
        browserName : 'chrome'
      }
    }
  }
};